<?php

// autoload_psr4.php @generated by Composer

$vendorDir = dirname(dirname(__FILE__));
$baseDir = $vendorDir;

return array(
    'Patchwork\\' => array($vendorDir . '/patchwork/utf8/src/Patchwork'),
);
