<?php

// autoload_static.php @generated by Composer

namespace Composer\Autoload;

class ComposerStaticInit62b161e184b27a13fd067a93fe2a6ff1
{
    public static $prefixLengthsPsr4 = array (
        'P' => 
        array (
            'Patchwork\\' => 10,
        ),
    );

    public static $prefixDirsPsr4 = array (
        'Patchwork\\' => 
        array (
            0 => __DIR__ . '/..' . '/patchwork/utf8/src/Patchwork',
        ),
    );

    public static $classMap = array (
        'Normalizer' => __DIR__ . '/..' . '/patchwork/utf8/src/Normalizer.php',
    );

    public static function getInitializer(ClassLoader $loader)
    {
        return \Closure::bind(function () use ($loader) {
            $loader->prefixLengthsPsr4 = ComposerStaticInit62b161e184b27a13fd067a93fe2a6ff1::$prefixLengthsPsr4;
            $loader->prefixDirsPsr4 = ComposerStaticInit62b161e184b27a13fd067a93fe2a6ff1::$prefixDirsPsr4;
            $loader->classMap = ComposerStaticInit62b161e184b27a13fd067a93fe2a6ff1::$classMap;

        }, null, ClassLoader::class);
    }
}
